apiVersion: v1 
kind: ConfigMap
metadata:
  name: db-config
data:
  PGDATA: "/var/lib/postgresql/data/db"
---
apiVersion: v1 
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  POSTGRES_USER: YWRtaW4=
  POSTGRES_PASSWORD: YWRtaW4=
  POSTGRES_DB: ZGV2b3BzbGFicw==
---
apiVersion: v1
kind: Secret
metadata:
  name: catalogo-secret
type: Opaque
data:
  DB_HOST: ZGI=
  DB_USER: YWRtaW4=
  DB_PASSWORD: YWRtaW4=
  DB_DATABASE: ZGV2b3BzbGFicw==
---
apiVersion: v1 
kind: ConfigMap
metadata:
  name: frontend-config
data:
  BASE_URL: "https://api.konzelmann.com.br"
